[package]
name = "toy-vo"
version = "0.1.0"
edition = "2024"
authors = ["Powei Lin <poweilin1994@gmail.com>"]
exclude = ["configs", "examples", "docs"]
license = "GPL-2.0-or-later"
description = "A very simple stereo visual odometry library"
homepage = "https://github.com/powei-lin/toy_vo"
repository = "https://github.com/powei-lin/toy_vo"
keywords = ["visual-odometry", "robotics"]
categories = ["data-structures", "science", "mathematics"]

[lib]
crate-type = ["lib", "cdylib"]

[features]
default = []
python = ["pyo3", "numpy"]

[dependencies]
anyhow = "1.0.102"
camera-intrinsic-model = "0.8.1"
image = { version = "0.25", default-features = false, features = ["png"] }
log = "0.4.29"
nalgebra = "0.34"
numpy = { version = "0.28", optional = true }
patch-tracker = "0.4.0"
pyo3 = { version = "0.28", features = ["extension-module", "abi3", "abi3-py310"], optional = true }
rand = "0.10.1"
rayon = "1.12.0"
serde = "1"
serde_json = "1"
sqpnp_simple = "0.2.0"
tiny-solver = "0.18.0"

[dev-dependencies]
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
fastrand = "2.4.1"
glob = "0.3.3"
rerun = "0.32"
